import React, { FC } from 'react';
import { StyleProp, View, ViewStyle } from 'react-native';
import WebView from 'react-native-webview';

interface CustomWebViewProps {
  strings: string; //string generated by rich text
  style?: StyleProp<ViewStyle>;
  loading?: boolean;
}

export const CustomWebView: FC<CustomWebViewProps> = ({ strings, style = { flex: 1 } }) => {
  return (
    <View style={style}>
      <WebView
        source={{ html: strings }}
        originWhitelist={['*']}
        allowUniversalAccessFromFileURLs={true}
        androidHardwareAccelerationDisabled={true} // false will cause Android phones to crash in version 9 and above
        geolocationEnabled={false}
        mixedContentMode={'always'}
        javaScriptEnabled={true}
      />
    </View>
  );
};
