
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts to edit in env.json then generate script */
/***********************************************/
export default {
  "API_URL": "https://gorest.co.in/public/v2",
  "ENV": "development",
  "TOKEN": "0b4c0fa225e4e432de7e51fe13691e86e27ac12a360ca251bf714eeb00942325",
  "GRAPHQL_API_ENDPOINT": "http://localhost:1337/graphql"
};
