
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/
export default {
  "API_URL": "https://ghibliapi.herokuapp.com",
  "ENV": "development"
};
