
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/
export default {
  "API_URL": "https://gorest.co.in/public/v1",
  "ENV": "development",
  "Token": "0b4c0fa225e4e432de7e51fe13691e86e27ac12a360ca251bf714eeb00942325"
};
